-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#161217', -- 背景
  base01 = '#100d12', --较浅的背景色
  base02 = '#1e1a20',
  base03 = '#dfb8f6', -- 键盘字符，匹配大括号
  base04 = '#cdc3ce',
  base05 = '#dfb8f6', -- 括号，运算符
  base06 = '#332f35',
  base07 = '#3c383e',

  base08 = '#f4b7b9',-- 变量名
  base09 = '#efdcf5', -- 整数、布尔值 (True/False)。
  base0A = '#d2c1d9', --类名 (Class)、搜索匹配到的背景
  base0B = '#dfb8f6', -- 字符串
  base0C = '#f4b7b9',
  base0D = '#593a6e', -- 函数名
  base0E = '#d2c1d9', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e9e0e8', -- 选中文字背景
  fg = '#161217', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#968e98', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f4b7b9',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#d2c1d9',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#725188',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#221e24', --底边
  fg = '#dfb8f6',
})
